Initializing sortedatab.cycle to zero when sorting SPHatab
... so that the list of accbodys is actually sorted on each
rank. Without this change, an SPH+gravity calculation will fail with

ERROR: Proc # main.c (832) in main :
Key mismatch in acc table